services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'

  app:
    image: 'eclipse-temurin:23-jre'
    volumes:
      - './target:/app'
    working_dir: /app
    command: sh -c "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar *.jar"
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    ports:
      - '5005:5005'
      - '8080:8080'
    depends_on:
      - mysql